#!/usr/bin/env bash

base_dir=$(dirname "$0")
cd "$base_dir"/../../../ || exit 1
APPDIR=$(pwd)

case $1 in
appname)
  APPNAME=$2 || echo -e "give me your project name"
  cd ..
  mv mirage_microservice "$APPNAME"
  # shellcheck disable=SC2164
  cd "$APPNAME"
  APPDIR=$(pwd)
  # TO DO
  ;;
removegit)
  rm -rf .git
  ;;
*)
  echo -e "mirage [changename project_name|removegit]"
esac